#pragma once

#include "GpApiMethod.hpp"
#include "GpApiMethodFactory.hpp"
#include "GpApiRqIfDesc.hpp"
#include "GpApiRsIfDesc.hpp"
#include "GpApiRqBaseDesc.hpp"
#include "GpApiRsBaseDesc.hpp"
#include "GpApiMethodsManager.hpp"
#include "GpApiCli.hpp"
#include "GpApiCliTransport.hpp"
#include "GpApiCliTransportFactory.hpp"
#include "GpApiCliTransportHttpFactory.hpp"
#include "GpApiSrvRequestHandlerHttp.hpp"
#include "GpApiTypeDetectorJsonFactory.hpp"
#include "GpApiVoidDesc.hpp"
